inputSet:
  identifier: "dev"
  name: "dev"
  tags: {}
  orgIdentifier: "default"
  projectIdentifier: "tiger"
  pipeline:
    identifier: "zztestcanarydeployment"
    stages:
    - stage:
        identifier: "Canary_Deploy"
        type: "Deployment"
        spec:
          service:
            serviceInputs:
              serviceDefinition:
                type: "Kubernetes"
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: "http-echo"
                      sources:
                      - identifier: "http-echo"
                        type: "DockerRegistry"
                        spec:
                          tag: "<+input>"
          environment:
            environmentRef: "cdtooling2eksv2"
        variables:
        - name: "manifest_branch"
          type: "String"
          value: "main"
        - name: "tfvars_branch"
          type: "String"
          value: "main"
        - name: "tfconfig_branch"
          type: "String"
          value: "main"
