inputSet:
  identifier: "dev"
  name: "dev"
  tags: {}
  orgIdentifier: "default"
  projectIdentifier: "tiger"
  pipeline:
    identifier: "zztestcanarydeployment"
    stages:
    - stage:
        identifier: "Provision_Infrastructure"
        type: "Custom"
        variables:
        - name: "target_env"
          type: "String"
          value: "dev"
    - stage:
        identifier: "Canary_Deploy_App"
        type: "Deployment"
        spec:
          service:
            serviceInputs:
              serviceDefinition:
                type: "Kubernetes"
                spec:
                  manifests:
                  - manifest:
                      identifier: "zztest"
                      type: "HelmChart"
                      spec:
                        store:
                          type: "Github"
                          spec:
                            branch: "jared-wip"
          execution:
            steps:
            - stepGroup:
                identifier: "canaryDepoyment"
                steps:
                - step:
                    identifier: "canaryDeployment"
                    type: "K8sCanaryDeploy"
                    spec:
                      instanceSelection:
                        type: "Count"
                        spec:
                          count: 2
