pipeline:
  name: zztest-canary-deployment
  identifier: zztestcanarydeployment
  projectIdentifier: tiger
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Approve to Start Deployment
        identifier: Approve_to_Start_Deployment
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Get Environment from Image
                  identifier: Get_Environment_from_Image
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          BUILD_TAG="<+stage.variables.image_tag>"
                          ENV_NAME=$(echo "${BUILD_TAG}" | sed 's/\(.*\)-.*-deploy$/\1/')
                          echo $BUILD_TAG
                          echo $ENV_NAME
                    environmentVariables: []
                    outputVariables:
                      - name: ENV_NAME
                        type: String
                        value: ENV_NAME
                      - name: BUILD_TAG
                        type: String
                        value: BUILD_TAG
                  timeout: 10m
              - step:
                  name: Approve to Start Deployment
                  identifier: Approve_to_Start_Deployment
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    approverInputs: []
                    approvalMessage: Approve to start deployment to <+pipeline.stages.Approve_to_Start_Deployment.spec.execution.steps.Get_Environment_from_Image.output.outputVariables.ENV_NAME>
                  when:
                    stageStatus: Success
                    condition: <+pipeline.stages.Approve_to_Start_Deployment.spec.execution.steps.Get_Environment_from_Image.output.outputVariables.ENV_NAME> == "prod" or <+pipeline.stages.Approve_to_Start_Deployment.spec.execution.steps.Get_Environment_from_Image.output.outputVariables.ENV_NAME> == "rc"
                  failureStrategies: []
        tags: {}
        when:
          pipelineStatus: Success
        variables:
          - name: image_tag
            type: String
            default: <+trigger.artifact.build>
            description: ""
            value: <+input>
    - stage:
        name: Canary Deploy
        identifier: Canary_Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: zztest
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: <+pipeline.stages.Approve_to_Start_Deployment.spec.execution.steps.Get_Environment_from_Image.output.outputVariables.ENV_NAME>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: cdtooling2eksv2
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Generate Provisioner ID
                  identifier: Generate_Provisioner_ID
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: provisioner_id=$RANDOM
                    environmentVariables: []
                    outputVariables:
                      - name: provisioner_id
                        type: String
                        value: provisioner_id
                  timeout: 10m
              - stepGroup:
                  name: Provision Infrastructure
                  identifier: Provision_Infrastructure
                  steps:
                    - step:
                        type: TerraformPlan
                        name: Terraform Plan
                        identifier: Terraform_Plan
                        spec:
                          configuration:
                            command: Apply
                            workspace: zztest-<+infra.namespace>
                            configFiles:
                              store:
                                type: Github
                                spec:
                                  gitFetchType: Branch
                                  connectorRef: mfjhellman
                                  repoName: harness-test-app
                                  folderPath: deploy/terraform
                                  branch: <+pipeline.stages.Approve_to_Start_Deployment.spec.execution.steps.Get_Environment_from_Image.output.outputVariables.ENV_NAME>
                            secretManagerRef: harnessSecretManager
                            varFiles:
                              - varFile:
                                  type: Remote
                                  identifier: from repo
                                  spec:
                                    store:
                                      type: Github
                                      spec:
                                        gitFetchType: Branch
                                        repoName: harness-test-app
                                        branch: <+pipeline.stages.Approve_to_Start_Deployment.spec.execution.steps.Get_Environment_from_Image.output.outputVariables.ENV_NAME>
                                        paths:
                                          - deploy/terraform/vars/<+env.name>.tfvars
                                        connectorRef: mfjhellman
                              - varFile:
                                  identifier: from harness vars
                                  spec:
                                    content: env="<+infra.namespace>"
                                  type: Inline
                          provisionerIdentifier: zztest<+execution.steps.Provision_Infrastructure.steps.Generate_Provisioner_ID.output.outputVariables.provisioner_id>
                        timeout: 10m
                    - step:
                        type: TerraformApply
                        name: Terraform Apply
                        identifier: Terraform_Apply
                        spec:
                          configuration:
                            type: InheritFromPlan
                          provisionerIdentifier: zztest<+execution.steps.Provision_Infrastructure.steps.Generate_Provisioner_ID.output.outputVariables.provisioner_id>
                        timeout: 10m
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.teardown> == "false"
                  failureStrategies: []
                  delegateSelectors:
                    - ""
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDepoyment
                  steps:
                    - step:
                        type: K8sApply
                        name: Manage Base Resources
                        identifier: Manage_Base_Resources
                        spec:
                          filePaths:
                            - base/namespace.yaml
                            - base/ingress.yaml
                            - base/service.yaml
                          skipDryRun: false
                          skipSteadyStateCheck: false
                          skipRendering: false
                          overrides:
                            - manifest:
                                identifier: " base"
                                type: Values
                                spec:
                                  store:
                                    type: Github
                                    spec:
                                      connectorRef: mfjhellman
                                      gitFetchType: Branch
                                      paths:
                                        - deploy/k8s/base/values.yaml
                                      repoName: harness-test-app
                                      branch: main
                        timeout: 10m
                        failureStrategies: []
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            spec:
                              percentage: 50
                            type: Percentage
                          skipDryRun: false
                        failureStrategies: []
                    - step:
                        type: Verify
                        name: Verify via New Relic
                        identifier: Verify_via_New_Relic
                        spec:
                          type: Canary
                          monitoredService:
                            type: Default
                            spec: {}
                          spec:
                            sensitivity: HIGH
                            duration: 5m
                            deploymentTag: <+serviceConfig.artifacts.primary.tag>
                        timeout: 2h
                        failureStrategies:
                          - onFailure:
                              errors:
                                - Verification
                              action:
                                type: ManualIntervention
                                spec:
                                  timeout: 2h
                                  onTimeout:
                                    action:
                                      type: StageRollback
                          - onFailure:
                              errors:
                                - Unknown
                              action:
                                type: ManualIntervention
                                spec:
                                  timeout: 2h
                                  onTimeout:
                                    action:
                                      type: Ignore
                        when:
                          stageStatus: Success
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec:
                          skipDryRun: false
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.teardown> == "false"
                  failureStrategies: []
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDepoyment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.teardown> == "false"
                  failureStrategies: []
              - stepGroup:
                  name: Teardown
                  identifier: Teardown
                  steps:
                    - step:
                        type: K8sDelete
                        name: Destroy Namespace
                        identifier: Destroy_Namespace
                        spec:
                          deleteResources:
                            type: ReleaseName
                            spec:
                              deleteNamespace: true
                        timeout: 10m
                    - step:
                        type: TerraformDestroy
                        name: Destroy Infra
                        identifier: Destroy_Infra
                        spec:
                          configuration:
                            type: InheritFromApply
                          provisionerIdentifier: zztest<+execution.steps.Provision_Infrastructure.steps.Generate_Provisioner_ID.output.outputVariables.provisioner_id>
                        timeout: 10m
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.teardown> == "true"
                  failureStrategies: []
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: name
            type: String
            description: Application name as used in k8s resources
            value: hello-world
        when:
          pipelineStatus: Success
  variables:
    - name: teardown
      type: String
      default: "false"
      description: ""
      value: <+input>
