pipeline:
  projectIdentifier: tiger
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Canary Deploy App
        identifier: Canary_Deploy_App
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: zztest
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  manifests:
                    - manifest:
                        identifier: zztest
                        type: HelmChart
                        spec:
                          store:
                            type: Github
                            spec:
                              branch: <+input>
          environment:
            environmentRef: cdtooling2eksv2
            deployToAll: false
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDepoyment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: <+input>
                          skipDryRun: false
                        failureStrategies: []
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  identifier: zztestjustcanarydeployment
  name: zztest-just-canary-deployment
