pipeline:
  name: zztest-canary-deployment
  identifier: zztestcanarydeployment
  projectIdentifier: tiger
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Provision Infrastructure
        identifier: Provision_Infrastructure
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: Terraform Plan
                  identifier: Terraform_Plan
                  spec:
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          type: Github
                          spec:
                            gitFetchType: Branch
                            connectorRef: mfjhellman
                            repoName: harness-test-app
                            branch: jared-wip
                            folderPath: deploy/terraform
                      secretManagerRef: harnessSecretManager
                    provisionerIdentifier: zztest
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: Approve Plan
                  identifier: Approve_Plan
                  spec:
                    approvalMessage: Review the plan and make sure all changes are expected
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: TerraformApply
                  name: Terraform Apply
                  identifier: Terraform_Apply
                  spec:
                    configuration:
                      type: InheritFromPlan
                    provisionerIdentifier: zztest
                  timeout: 10m
        tags: {}
